### ISSUE TITLE
A uncaught exeption occured 

### ISSUE THREAD

**Issue by pimagical** [michbeck100/pimatic-hap#10]
After installing and configuring pimatic-hab using Eve it worked very good for a few hours.
This error message I got the next day. Restarting pimatic won't fix the problem. And the Eve app tells me the devices are unreacable. The homekit server can't be found anymore.

error [pimatic]: A uncaught exception occured: Error: dns service error: unknown at Advertisement.on_service_registered (/home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:42:24) at SocketWatcher.MDNSService.self.watcher.callback (/home/pi/pimatic-app/node_modules/pimatic-hap/node_modules/hap-nodejs/node_modules/mdns/lib/mdns_service.js:18:40) This is most probably a bug in pimatic or in a module, please report it!

@michbeck100 what can I do to fix this?

**Comment by pimagical** [comment]
After installing a normal pimatic update (pimatic-homeduino) and a restart it started to work again!

**Comment by rspaargaren** [comment]
I have received the same error now also several times. I have a clean raspbian system and a fresh install of pimatic on it. Nothting else installed.

**Comment by michbeck100** [comment]
First of all, did you follow the instructions on https://github.com/michbeck100/pimatic-hap/blob/master/README.md? libnss-mdns and libavahi-compat-libdnssd-dev have to be installed before running pimatic-hap. If thats not the problem maybe https://github.com/agnat/node_mdns/issues/104 may help you. Like i told everyone with error before, the problem comes from the mdns library and not from pimatic-hap.
