### ISSUE TITLE
Property "hap" is not a valid property

### ISSUE THREAD

**Issue by ageorgios** [michbeck100/pimatic-hap#26]
Hello, I have this configuration, but I get this error:

Invalid config of device "switch": Property "hap" is not a valid property

"devices": [
    {
      "id": "home-switch",
      "name": "Fritz outlet",
      "class": "FritzOutlet",
      "ain": "087610239316",
      "hap": {
          "service": "Lightbulb",
          "exclude": false
           }
    }
  ]

**Comment by michbeck100** [comment]
Actually this should just be a warning. Are you using version 0.5.6 or the latest github HEAD?

**Comment by ageorgios** [comment]
It is in red and consider it as an error
I also have this error: Cannot find module 'hap-nodejs/node_modules/debug'
I am using 0.5.6 as it installed automatically from pimatic startup
node = 0.10.42

and cannot discover from HMCatalog official Apple Sample App for Homekit

Any ideas? Thank you.

**Comment by michbeck100** [comment]
Since https://github.com/pimatic/pimatic/commit/8ed9f008fe6470e8ff9af2365f2e914d9a2676dd this is just a log message (with error level). The second error is more serious. I would suggest to delete the pimatic-hap folder from node_modules completely and restart pimatic. This will install the plugin again incl. all dependencies.

**Comment by ageorgios** [comment]
that fixed the issue with debug and now it works
thank you! great work!

p.s. the warning still appears and ignored
