### ISSUE TITLE
Config in type of switch

### ISSUE THREAD

**Issue by rspaargaren** [michbeck100/pimatic-hap#6]
Would there be a possibility to change the type of switch. Now dimmer is indicated as a lamp with power switch. To Some kaku switches I have a lamp connected, would be nice if they can be identified as lamps in EVE

**Comment by michbeck100** [comment]
You can configure this by yourself in EVE. Just enter Settings -> Devices in EVE. Here you can set the type for every switch yourself. The default type for Switches is 'Switch'. I did this on purpose, because not every switch is connected to a lamp. In a future release i'm planning to make the accessory type configurable. But this is low priority for now.

**Comment by rspaargaren** [comment]
Yes indeed found it! It is quite hidden in eve:
Settings>accesoires>"the device">features>used for>light bulb....
Thanks for the update
